---
title: "Tgondii_screen-v1"
output: html_document
---


```{r load-data}
##########################################
# first version of the data Einar shared #
##########################################
regression_data <- readr::read_csv(
  "~/Downloads/regression_data.csv",
  show_col_types = FALSE) |>
  tidyr::separate_wider_delim(
    cols = prc,
    names = c("plate", "row", "column"),
    delim = "_") |>
  dplyr::mutate(
    plate = plate |> stringr::str_replace("plate", "") |> as.integer(),
    row = row |> stringr::str_replace("r", "") |> as.integer(),
    column = column |> stringr::str_replace("c", "") |> as.integer()) |>
  dplyr::arrange(plate, row, column) |>
  dplyr::mutate(
    well = dplyr::row_number(),
    .before = 1)
sequencing_data <- readr::read_csv(
  "~/Downloads/sequencing_mixed_condition_column_3.csv",
  show_col_types = FALSE) |>
  dplyr::select(-`...1`) |>
  dplyr::mutate(
    plate = plate |> stringr::str_replace("plate", "") |> as.integer(),
    row = row |> stringr::str_replace("r", "") |> as.integer(),
    column = column |> stringr::str_replace("c", "") |> as.integer(),
    .before = 1) |>
  dplyr::arrange(plate, row, column) |>
  dplyr::mutate(
    well = dplyr::row_number(),
    .before = 1)
```

```{r summarize-data}

plot <- regression_data |>
  dplyr::select(
    well,
    count = cell_count_maxvit) |>
  spaCRPower::plot_cells_per_well()

plot
```

```{r model-cell-count}

model_data <- regression_data |>
  dplyr::select(
    count = cell_count_maxvit)

model <- brms::brm(
  formula = count ~ 1,
  family = Gamma(link = "log"),
  data = model_data,
  backend = "cmdstanr",
  chains = 0)

model_fit <- model |>
   stats::update(
      newdata = model_data,
      chains = 4,
      iter = 4000,
      cores = 4,
      control = list(
        max_treedepth = 12),
      backend = "cmdstanr",
      recompile = FALSE)

model_estimate <-   model_fit |>
    posterior::summarize_draws() |>
    dplyr::filter(
      variable %in% c("Intercept", "shape"))


epred_draws <- model_fit |>
  tidybayes::add_epred_draws(
    newdata = model_data,
    ndraws = 50)
pp_data <- model_fit |>
  tidybayes::add_predicted_draws(
    newdata = model_data,
    ndraws = 200) |>
  ggdist::median_qi(.width = c(0.5, 0.8, 0.9))

spaCRPower::plot_cells_per_well(
  data = epred_draws |>
    dplyr::group_by()
)


ggplot2::ggplot() +
  ggplot2::theme_bw() +
  ggplot2::theme(legend.position = "bottom") +

  ggplot2::geom_(
    data = pp_data,
    mapping = ggplot2::aes(
      x = .data[[treatment_variable]],
      y = .data[[response_variable]],
      group = .data[[".draw"]]),
    linewidth = 0.4,
    alpha = 0.2,
    color = "blueviolet")


ggplot2::ggplot()


```
